[tool.briefcase]
project_name = "instawow-gui"
bundle = "org.instawow"
version = "0.0.0"
url = "https://github.com/layday/instawow"
license = "GNU General Public License v3 (GPLv3)"
author = "layday"
author_email = "layday@protonmail.com"

[tool.briefcase.app.instawow-gui-wrapper]
formal_name = "instawow-gui"
description = "GUI for the World of Warcraft add-on manager instawow"
icon = "src/instawow_gui/resources/instawow_gui"
sources = ["src/instawow_gui_wrapper"]
requires = [
  "..[gui]",
  "certifi",
]
